apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecovangel-skyward-challenge.fullname" . }}
  labels:
    {{ include "ecovangel-skyward-challenge.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ecovangel-skyward-challenge.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ecovangel-skyward-challenge.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: ecovangel/skyward-devops-challenge:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
