apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecovangel-skyward-challenge.fullname" . }}
  labels:
    {{ include "ecovangel-skyward-challenge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ include "ecovangel-skyward-challenge.name" . }}
